### ISSUE TITLE
Deploy to Azure button error

### ISSUE THREAD

**Issue by snpdev** [microsoft/RockPaperScissorsLizardSpock#1]
Loved the "App Development for Everyone" Ignite keynote and demos. Kudos to all involved!

I'm giving rpsls a go today and have this issue to report.

In Step 1 - Option 1: Creating infrastructure using Azure Portal, I click on the Deploy to Azure button. This opens Azure Portal with the following error:

> There was an error loading the template from URI 'https://raw.githubusercontent.com/OriolBonjoch/RPSLS/master/Deploy/arm/deployment.json'. Ensure that the template is publicly accessible and does not have any comments.

I was able to copy and paste [deployment.json](https://github.com/microsoft/RockPaperScissorsLizardSpock/blob/master/Deploy/arm/deployment.json) into a custom template in my Azure subscription and deploy from there. 

Apart from the Service Principal Id and Secret, the Kv_object Id is also required. A minor point perhaps, but the Kv_object Id requirement is not mentioned in the README.md.

The deployment succeeded showing the following 10 resources:

![image](https://user-images.githubusercontent.com/1825479/68404274-48475c80-014c-11ea-8695-b6e6fa3a9419.png)

**Comment by dasanagu** [comment]
Thank you very much @snpdev fixed in commit [42a446](https://github.com/microsoft/RockPaperScissorsLizardSpock/commit/42a44699a8d7684007f448eeb79feb083b7446fc).
