### ISSUE TITLE
Running app locally with docker desktop

### ISSUE THREAD

**Issue by emile-cronje** [microsoft/RockPaperScissorsLizardSpock#31]
Good day

I have problems running the app locally with docker desktop.

I cloned the repository, opened in VS 2019, built the app, everything good. I have RPSLS.Web as startup project and press F5.
I have docker desktop running, but get the following message in the browser:
Could not reconnect to the server.
Have fun defeating our bot with your language of choice!

In the output window I get the message:
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit '9bTXHbA9Q5vH-LPXg4wBw0SEuZMcT71Huwvutl0nqBc'.
System.InvalidOperationException: Cannot consume scoped service 'RPSLS.Web.Clients.IConfigurationManagerClient' from singleton 'Microsoft.Extensions.Options.IOptions`1[RPSLS.Web.Config.MultiplayerSettings]'.

What am I missing?
Regards

**Comment by dsrodenas** [comment]
Hello,

From Visual Studio the startup project must be docker-compose. The docker-compose will build and run all the projects, some of them (PHP, Java, Node...) are not included in the Visual Studio solution but are in the Docker-compose files. So setting as startup project docker compose and pressing F5 should work.

![image](https://user-images.githubusercontent.com/25981928/79727212-53eaa200-82ec-11ea-831f-1f5ce7ecb47f.png)

I hope it helps.

Bet regards.

**Comment by emile-cronje** [comment]
Hello David

Thank you, problem solved.

Regards
