### ISSUE TITLE
Link on docs.microsoft.com is broken

### ISSUE THREAD

**Issue by whaakman** [microsoft/RockPaperScissorsLizardSpock#33]
The buttons "Browse Code" and "Deploy to Azure" are no longer valid as the branch name was changed to "main". Confirmed that URLs are working when changing to main.

Article: https://docs.microsoft.com/en-us/samples/microsoft/rockpaperscissorslizardspock/azure-rock-paper-scissors/

**Comment by isaacrlevin** [comment]
This is fixed
