### ISSUE TITLE
Deploying services fails

### ISSUE THREAD

**Issue by snpdev** [microsoft/RockPaperScissorsLizardSpock#6]
I have complete and utter failure on the [Deploying services](https://github.com/microsoft/RockPaperScissorsLizardSpock#deploying-services) step :anguished:.   As time permits today, I'll review logs and add information to this issue. If there are particular logs that the maintainers would like to see, please comment. Thanks
```
$ kubectl get po
NAME                                                 READY   STATUS              RESTARTS   AGE
rpsls-dotnet-dotnet-player-random-5cdfffbff6-pnvxn   0/1     ImagePullBackOff    0          6m3s
rpsls-game-game-api-d96656ffb-wdnvb                  0/1     ContainerCreating   0          5m52s
rpsls-java-java-player-random-69977b48d4-hjt45       0/1     ErrImagePull        0          5m57s
rpsls-node-node-player-paper-696fc4f975-lrl82        0/1     ImagePullBackOff    0          6m2s
rpsls-php-php-player-random-85d89489b6-mngvh         0/1     ErrImagePull        0          5m54s
rpsls-python-python-player-random-76bbdb94f9-x2rd6   0/1     ErrImagePull        0          5m56s
rpsls-web-865fb687c4-t5qcl                           0/2     ImagePullBackOff    0          5m50s
```

**Comment by snpdev** [comment]
I found the problem. The default tag is `latest`. The tag must be set to `v1`. Adding the tag parameter solves the problem. This is the command that I ran (anonymized):
```
 .\Deploy-Images-Aks.ps1 -resourceGroup $resourceGroup -aksName $myAks -acrName $myAcr -valuesFile 'C:\Work\source\RockPaperScissorsLizardSpock\Deploy\helm\__values\gvalues.yaml' -kvPassword 'mypassword' -tag 'v1'
```

**Comment by eiximenis** [comment]
We need to update as its a bit confusing. We are using `v1` as the tag example in the `Build-Push.ps1` script but then we forgot to add this tag in the example of `Deploy-Images.Aks.ps1`.

If we use `v1` in the 1st place should use in the 2nd too, to avoid this kind of errors.

Thanks for reporting @snpdev

**Comment by olgamarti** [comment]
We updated the documentation in PR #11
