### ISSUE TITLE
CRLF to LF for entrypoint.sh and mvnw

### ISSUE THREAD

**Issue by vermegi** [microsoft/RockPaperScissorsLizardSpock#8]
Just as an FYI: I had trouble with the JavaPlayer Dockerfile build and the ModelUploader.Web Dockerfile build. 

JavaPlayer Dockerfile: 

line 10: RUN ./mvnw package

./mvnw couldn't be found at docker build

ModelUploader.Web Dockerfile: 

line 28: CMD /app/entrypoint.sh 

Made the container crash at run time. 

Both issues were related to the same problem. Both ./mvnw and entrypoint.sh were using Windows line endings (CRLF) as opposed to Unix ones (LF). Opening each file with Notepad++ - Edit - EOL - change to LF, fixed this error for me. 

And I though I'd just leave this FYI out here for anyone else bumping into this issue. Maybe mention in install doc for awareness.

**Comment by eiximenis** [comment]
I've added a .gitattributes that should solve the issue.
Its commit #9fbc0be5eb4ecd6a13bd3044e88a588366753888

**Comment by olgamarti** [comment]
Solved in commit https://github.com/microsoft/RockPaperScissorsLizardSpock/commit/9fbc0be5eb4ecd6a13bd3044e88a588366753888
